export const AMPLITUDE_EVENTS = {
  // 회원가입 관련
  SIGNUP_INIT: 'Signup_Init',
  SIGNUP_ROUTE_ENTERED: 'Signup_Route_Entered',
  SIGNUP_UNIVERSITY: 'Signup_university',
  SINGUP_UNIVERSITY_DETAILS: 'Singup_university_details',
  SIGNUP_PROFILE_IMAGE: 'Signup_profile_image',
  SIGNUP_PROFILE_IMAGE_ERROR: 'Signup_profile_image_error',
  SIGNUP_PROFILE_INVITE_CODE_ERROR: 'Signup_profile_invite_code_error',

  // 나이/인증 관련
  SIGNUP_AGE_CHECK_FAILED: 'Signup_AgeCheck_Failed',
  SIGNUP_PHONE_BLACKLIST_FAILED: 'Signup_PhoneBlacklist_Failed',
  SIGNUP_ERROR: 'Signup_Error',

  // 관심사/프로필 관련
  INTEREST_HOLD: 'Interest_Hold',
  INTEREST_STARTED: 'Interest_Started',
  PROFILE_STARTED: 'Profile_Started',

  // 결제 관련
  GEM_STORE_FIRST_SALE_7: 'GemStore_FirstSale_7',
  GEM_STORE_FIRST_SALE_16: 'GemStore_FirstSale_16',
  GEM_STORE_FIRST_SALE_27: 'GemStore_FirstSale_27',
  GEM_STORE_PAYMENT_SUCCESS: 'GemStore_Payment_Success',

  // 기타
  SIGNUP_COMPLETE: 'signup_complete',
  IMAGE_UPLOAD: 'image_upload',
} as const;

export type AmplitudeEventKeys = keyof typeof AMPLITUDE_EVENTS;
export type AmplitudeEventValues = typeof AMPLITUDE_EVENTS[AmplitudeEventKeys];

// 특정 카테고리별 이벤트 그룹
export const SIGNUP_EVENTS = {
  INIT: AMPLITUDE_EVENTS.SIGNUP_INIT,
  ROUTE_ENTERED: AMPLITUDE_EVENTS.SIGNUP_ROUTE_ENTERED,
  UNIVERSITY: AMPLITUDE_EVENTS.SIGNUP_UNIVERSITY,
  UNIVERSITY_DETAILS: AMPLITUDE_EVENTS.SINGUP_UNIVERSITY_DETAILS,
  PROFILE_IMAGE: AMPLITUDE_EVENTS.SIGNUP_PROFILE_IMAGE,
  PROFILE_IMAGE_ERROR: AMPLITUDE_EVENTS.SIGNUP_PROFILE_IMAGE_ERROR,
  PROFILE_INVITE_CODE_ERROR: AMPLITUDE_EVENTS.SIGNUP_PROFILE_INVITE_CODE_ERROR,
  COMPLETE: AMPLITUDE_EVENTS.SIGNUP_COMPLETE,
  AGE_CHECK_FAILED: AMPLITUDE_EVENTS.SIGNUP_AGE_CHECK_FAILED,
  PHONE_BLACKLIST_FAILED: AMPLITUDE_EVENTS.SIGNUP_PHONE_BLACKLIST_FAILED,
  ERROR: AMPLITUDE_EVENTS.SIGNUP_ERROR,
  IMAGE_UPLOAD: AMPLITUDE_EVENTS.IMAGE_UPLOAD,
} as const;

export const PAYMENT_EVENTS = {
  FIRST_SALE_7: AMPLITUDE_EVENTS.GEM_STORE_FIRST_SALE_7,
  FIRST_SALE_16: AMPLITUDE_EVENTS.GEM_STORE_FIRST_SALE_16,
  FIRST_SALE_27: AMPLITUDE_EVENTS.GEM_STORE_FIRST_SALE_27,
  PAYMENT_SUCCESS: AMPLITUDE_EVENTS.GEM_STORE_PAYMENT_SUCCESS,
} as const;

export const USER_BEHAVIOR_EVENTS = {
  INTEREST_HOLD: AMPLITUDE_EVENTS.INTEREST_HOLD,
  INTEREST_STARTED: AMPLITUDE_EVENTS.INTEREST_STARTED,
  PROFILE_STARTED: AMPLITUDE_EVENTS.PROFILE_STARTED,
} as const;