export const AMPLITUDE_EVENTS = {
  // 회원가입 퍼널 - View 이벤트 (화면 진입)
  SIGNUP_LOGIN_VIEW: 'Signup_Login_View',
  SIGNUP_AUTH_STARTED: 'Signup_Auth_Started',
  SIGNUP_UNIVERSITY_VIEW: 'Signup_University_View',
  SIGNUP_DETAILS_VIEW: 'Signup_Details_View',
  SIGNUP_PROFILE_VIEW: 'Signup_Profile_View',

  // 회원가입 퍼널 - 완료 이벤트
  SIGNUP_INIT: 'Signup_Init',
  SIGNUP_ROUTE_ENTERED: 'Signup_Route_Entered',
  SIGNUP_UNIVERSITY: 'Signup_university',
  SINGUP_UNIVERSITY_DETAILS: 'Singup_university_details',
  SIGNUP_PROFILE_IMAGE: 'Signup_profile_image',
  SIGNUP_PROFILE_IMAGE_ERROR: 'Signup_profile_image_error',
  SIGNUP_PROFILE_INVITE_CODE_ERROR: 'Signup_profile_invite_code_error',

  // 나이/인증 관련
  SIGNUP_AGE_CHECK_FAILED: 'Signup_AgeCheck_Failed',
  SIGNUP_PHONE_BLACKLIST_FAILED: 'Signup_PhoneBlacklist_Failed',
  SIGNUP_ERROR: 'Signup_Error',

  // 관심사/프로필 관련
  INTEREST_HOLD: 'Interest_Hold',
  INTEREST_STARTED: 'Interest_Started',
  PROFILE_STARTED: 'Profile_Started',

  // 결제 관련
  GEM_STORE_FIRST_SALE_7: 'GemStore_FirstSale_7',
  GEM_STORE_FIRST_SALE_16: 'GemStore_FirstSale_16',
  GEM_STORE_FIRST_SALE_27: 'GemStore_FirstSale_27',
  GEM_STORE_PAYMENT_SUCCESS: 'GemStore_Payment_Success',

  // 인앱 리뷰 관련
  IN_APP_REVIEW_ELIGIBLE: 'InAppReview_Eligible',
  IN_APP_REVIEW_PRE_PROMPT_SHOWN: 'InAppReview_PrePromptShown',
  IN_APP_REVIEW_PRE_PROMPT_RESPONSE: 'InAppReview_PrePromptResponse',
  IN_APP_REVIEW_REQUESTED: 'InAppReview_Requested',

  // 기타
  SIGNUP_COMPLETE: 'signup_complete',
  IMAGE_UPLOAD: 'image_upload',

  // 미호 멘트 관련
  MIHO_MESSAGE_SHOWN: 'Miho_Message_Shown',
} as const;

export type AmplitudeEventKeys = keyof typeof AMPLITUDE_EVENTS;
export type AmplitudeEventValues = typeof AMPLITUDE_EVENTS[AmplitudeEventKeys];

// 특정 카테고리별 이벤트 그룹
export const SIGNUP_EVENTS = {
  // View 이벤트 (화면 진입)
  LOGIN_VIEW: AMPLITUDE_EVENTS.SIGNUP_LOGIN_VIEW,
  AUTH_STARTED: AMPLITUDE_EVENTS.SIGNUP_AUTH_STARTED,
  UNIVERSITY_VIEW: AMPLITUDE_EVENTS.SIGNUP_UNIVERSITY_VIEW,
  DETAILS_VIEW: AMPLITUDE_EVENTS.SIGNUP_DETAILS_VIEW,
  PROFILE_VIEW: AMPLITUDE_EVENTS.SIGNUP_PROFILE_VIEW,
  // 완료 이벤트
  INIT: AMPLITUDE_EVENTS.SIGNUP_INIT,
  ROUTE_ENTERED: AMPLITUDE_EVENTS.SIGNUP_ROUTE_ENTERED,
  UNIVERSITY: AMPLITUDE_EVENTS.SIGNUP_UNIVERSITY,
  UNIVERSITY_DETAILS: AMPLITUDE_EVENTS.SINGUP_UNIVERSITY_DETAILS,
  PROFILE_IMAGE: AMPLITUDE_EVENTS.SIGNUP_PROFILE_IMAGE,
  PROFILE_IMAGE_ERROR: AMPLITUDE_EVENTS.SIGNUP_PROFILE_IMAGE_ERROR,
  PROFILE_INVITE_CODE_ERROR: AMPLITUDE_EVENTS.SIGNUP_PROFILE_INVITE_CODE_ERROR,
  COMPLETE: AMPLITUDE_EVENTS.SIGNUP_COMPLETE,
  AGE_CHECK_FAILED: AMPLITUDE_EVENTS.SIGNUP_AGE_CHECK_FAILED,
  PHONE_BLACKLIST_FAILED: AMPLITUDE_EVENTS.SIGNUP_PHONE_BLACKLIST_FAILED,
  ERROR: AMPLITUDE_EVENTS.SIGNUP_ERROR,
  IMAGE_UPLOAD: AMPLITUDE_EVENTS.IMAGE_UPLOAD,
} as const;

export const PAYMENT_EVENTS = {
  FIRST_SALE_7: AMPLITUDE_EVENTS.GEM_STORE_FIRST_SALE_7,
  FIRST_SALE_16: AMPLITUDE_EVENTS.GEM_STORE_FIRST_SALE_16,
  FIRST_SALE_27: AMPLITUDE_EVENTS.GEM_STORE_FIRST_SALE_27,
  PAYMENT_SUCCESS: AMPLITUDE_EVENTS.GEM_STORE_PAYMENT_SUCCESS,
} as const;

export const USER_BEHAVIOR_EVENTS = {
  INTEREST_HOLD: AMPLITUDE_EVENTS.INTEREST_HOLD,
  INTEREST_STARTED: AMPLITUDE_EVENTS.INTEREST_STARTED,
  PROFILE_STARTED: AMPLITUDE_EVENTS.PROFILE_STARTED,
} as const;