export enum UniversityName {
	배재대학교 = '배재대학교',
	충남대학교 = '충남대학교',
	대전보건대학교 = '대전보건대학교',
	대전대학교 = '대전대학교',
	한밭대학교 = '한밭대학교',
	한남대학교 = '한남대학교',
	건양대학교메디컬캠퍼스 = '건양대학교 메디컬캠퍼스',
	건양대학교창의융합캠퍼스 = '건양대학교 창의융합캠퍼스',
	KAIST = 'KAIST',
	건양대학교 = '건양대학교',
	목원대학교 = '목원대학교',
	을지대학교 = '을지대학교',
	우송대학교 = '우송대학교',
	고려대학교세종캠퍼스 = '고려대학교 세종캠퍼스',
	홍익대학교세종캠퍼스 = '홍익대학교 세종캠퍼스',
	한국교원대학교 = '한국교원대학교',

	공주대학교 = '공주대학교',
	공주교육대학교 = '공주교육대학교',
	충북대학교 = '충북대학교',
	청주교육대학교 = '청주교육대학교',
	경성대학교 = '경성대학교',
	고신대학교 = '고신대학교',
	부경대학교 = '부경대학교',
	국립부경대학교 = '국립부경대학교',
	한국해양대학교 = '한국해양대학교',
	국립한국해양대학교 = '국립한국해양대학교',
	동명대학교 = '동명대학교',
	동서대학교 = '동서대학교',
	동아대학교 = '동아대학교',
	동의대학교 = '동의대학교',
	부산가톨릭대학교 = '부산가톨릭대학교',
	부산교육대학교 = '부산교육대학교',
	부산대학교 = '부산대학교',
	가야대학교 = '가야대학교',
	부산외국어대학교 = '부산외국어대학교',
	신라대학교 = '신라대학교',
	영신대학교 = '영신대학교',
	인제대학교 = '인제대학교',
	부산과학기술대학교 = '부산과학기술대학교',
	동의과학대학교 = '동의과학대학교',
	부산여자대학교 = '부산여자대학교',
	부산경상대학교 = '부산경상대학교',
	부산보건대학교 = '부산보건대학교',
	부산예술대학교 = '부산예술대학교',
	김해대학교 = '김해대학교',
	동원과학기술대학교 = '동원과학기술대학교',
	경남정보대학교 = '경남정보대학교',
	대동대학교 = '대동대학교',
	'한국폴리텍 VII 대학 부산캠퍼스' = '한국폴리텍 VII 대학 부산캠퍼스',
	'한국폴리텍 VII 대학 동부산캠퍼스' = '한국폴리텍 VII 대학 동부산캠퍼스',
	우송정보대 = '우송정보대',
	대전신학대학교 = '대전신학대학교',
	중부대학교 = '중부대학교',
	충북도립대학교 = '충북도립대학교',
	한국폴리텍 = '한국폴리텍',
	한국침례신학대학교 = '한국침례신학대학교',
	대덕대학교 = '대덕대학교',
	금강대학교 = '금강대학교',
	대전과학기술대학교 = '대전과학기술대학교',
	꽃동네대학교 = '꽃동네대학교',
	서원대학교 = '서원대학교',
	청주대학교 = '청주대학교',
	충북보건과학대학교 = '충북보건과학대학교',
	충청대학교 = '충청대학교',
	'한국폴리텍대학교 청주캠퍼스' = '한국폴리텍대학교 청주캠퍼스',

	경북대학교 = '경북대학교',
	경북과학대학교 = '경북과학대학교',
	경북보건대학교 = '경북보건대학교',
	경일대학교 = '경일대학교',
	계명대학교 = '계명대학교',
	계명문화대학교 = '계명문화대학교',
	구미대학교 = '구미대학교',
	금오공과대학교 = '금오공과대학교',
	김천대학교 = '김천대학교',
	대경대학교 = '대경대학교',
	대구가톨릭대학교 = '대구가톨릭대학교',
	대구경북과학기술원 = '대구경북과학기술원',
	대구공업대학교 = '대구공업대학교',
	대구과학대학교 = '대구과학대학교',
	대구교육대학교 = '대구교육대학교',
	대구대학교 = '대구대학교',
	대구보건대학교 = '대구보건대학교',
	대구예술대학교 = '대구예술대학교',
	대구한의대학교 = '대구한의대학교',
	대신대학교 = '대신대학교',
	수성대학교 = '수성대학교',
	영남대학교 = '영남대학교',
	영남신학대학교 = '영남신학대학교',
	영남외국어대학교 = '영남외국어대학교',
	영남이공대학교 = '영남이공대학교',
	영진전문대학교 = '영진전문대학교',
	호산대학교 = '호산대학교',
	경운대학교 = '경운대학교',
	'한국폴리텍대학교 구미캠퍼스' = '한국폴리텍대학교 구미캠퍼스',
	'한국폴리텍대학교 대구캠퍼스' = '한국폴리텍대학교 대구캠퍼스',
	'한국폴리텍대학교 영남융합기술캠퍼스' = '한국폴리텍대학교 영남융합기술캠퍼스',
	'한국폴리텍대학교 영주캠퍼스' = '한국폴리텍대학교 영주캠퍼스',

	// 천안
	국립공주대학교 = '국립공주대학교',
	나사렛대학교 = '나사렛대학교',
	남서울대학교 = '남서울대학교',

	백석대학교 = '백석대학교',
	상명대학교 = '상명대학교',

	한국기술교육대학교 = '한국기술교육대학교',
	유원대학교 = '유원대학교',
	호서대학교 = '호서대학교',
	연암대학교 = '연암대학교',
	'한국폴리텍 IV 대학 아산캠퍼스' = '한국폴리텍 IV 대학 아산캠퍼스',
	'한국폴리텍 I 대학 (서울캠퍼스)' = '한국폴리텍 I 대학 (서울캠퍼스)',
	한국체육대학교 = '한국체육대학교',
	서울대학교 = '서울대학교',
	서울과학기술대학교 = '서울과학기술대학교',
	화성의과학대학교 = '화성의과학대학교',
	협성대학교 = '협성대학교',
	한경국립대학교 = '한경국립대학교',
	한국항공대학교 = '한국항공대학교',
	한국공학대학교 = '한국공학대학교',

	'한국폴리텍 II 대학 인천캠퍼스' = '한국폴리텍 II 대학 인천캠퍼스',
	인천대학교 = '인천대학교',
	국립한국교통대학교 = '국립한국교통대학교',
	한국예술종합학교 = '한국예술종합학교',
	서울시립대학교 = '서울시립대학교',
	서울교육대학교 = '서울교육대학교',
	인덕대학교 = '인덕대학교',
	가천대학교 = '가천대학교',
	가톨릭대학교 = '가톨릭대학교',
	재능대학교 = '재능대학교',
	인하공업전문대학 = '인하공업전문대학',
	경인여자대학교 = '경인여자대학교',
	청운대학교 = '청운대학교',
	인하대학교 = '인하대학교',
	인천가톨릭대학교 = '인천가톨릭대학교',
	안양대학교 = '안양대학교',
	경인교육대학교 = '경인교육대학교',
	연세대학교국제캠퍼스 = '연세대학교국제캠퍼스',
	강남대학교 = '강남대학교',
	경기대학교 = '경기대학교',
	경동대학교 = '경동대학교',
	경희대학교 = '경희대학교',
	숭의여자대학교 = '숭의여자대학교',
	서일대학교 = '서일대학교',
	서울여자간호대학교 = '서울여자간호대학교',
	삼육보건대학교 = '삼육보건대학교',
	명지전문대학 = '명지전문대학',
	동양미래대학교 = '동양미래대학교',
	홍익대학교 = '홍익대학교',
	한양대학교 = '한양대학교',
	한성대학교 = '한성대학교',
	한국외국어대학교 = '한국외국어대학교',
	한국성서대학교 = '한국성서대학교',
	총신대학교 = '총신대학교',
	중앙대학교 = '중앙대학교',
	장로회신학대학교 = '장로회신학대학교',
	이화여자대학교 = '이화여자대학교',
	숭실대학교 = '숭실대학교',
	숙명여자대학교 = '숙명여자대학교',
	세종대학교 = '세종대학교',
	성신여자대학교 = '성신여자대학교',
	성공회대학교 = '성공회대학교',
	서울한영대학교 = '서울한영대학교',
	서울여자대학교 = '서울여자대학교',
	서울기독대학교 = '서울기독대학교',
	서경대학교 = '서경대학교',
	서강대학교 = '서강대학교',
	삼육대학교 = '삼육대학교',
	명지대학교 = '명지대학교',
	동덕여자대학교 = '동덕여자대학교',
	동국대학교 = '동국대학교',
	국민대학교 = '국민대학교',
	광운대학교 = '광운대학교',
	고려대학교 = '고려대학교',
	건국대학교 = '건국대학교',
	강서대학교 = '강서대학교',
	감리신학대학교 = '감리신학대학교',
	한양여자대학교 = '한양여자대학교',
	배화여자대학교 = '배화여자대학교',
	추계예술대학교 = '추계예술대학교',
	연세대학교 = '연세대학교',
	성균관대학교 = '성균관대학교',
	덕성여자대학교 = '덕성여자대학교',
	단국대학교 = '단국대학교',
	대진대학교 = '대진대학교',
	동양대학교 = '동양대학교',
	루터대학교 = '루터대학교',
	서울신학대학교 = '서울신학대학교',
	서울장신대학교 = '서울장신대학교',
	성결대학교 = '성결대학교',
	수원가톨릭대학교 = '수원가톨릭대학교',
	수원대학교 = '수원대학교',
	신한대학교 = '신한대학교',
	아신대학교 = '아신대학교',
	아주대학교 = '아주대학교',
	예원예술대학교 = '예원예술대학교',
	용인대학교 = '용인대학교',

	중앙승가대학교 = '중앙승가대학교',
	차의과학대학교 = '차의과학대학교',
	칼빈대학교 = '칼빈대학교',
	평택대학교 = '평택대학교',
	한세대학교 = '한세대학교',
	한신대학교 = '한신대학교',
	'한양대학교(ERICA)' = '한양대학교(ERICA)',
	순천향대학교 = '순천향대학교',
}

export const UniversityImage: Record<UniversityName, string> = {
	[UniversityName.배재대학교]: 'bju.png',
	[UniversityName.충남대학교]: 'cnu.png',
	[UniversityName.대전보건대학교]: 'dbu.png',
	[UniversityName.대전대학교]: 'dju.png',
	[UniversityName.한밭대학교]: 'hbu.png',
	[UniversityName.KAIST]: 'kaist.png',
	[UniversityName.한남대학교]: 'hnu.png',
	[UniversityName.건양대학교메디컬캠퍼스]: 'kyu.png',
	[UniversityName.건양대학교창의융합캠퍼스]: 'kyu.png',
	[UniversityName.건양대학교]: 'kyu.png',
	[UniversityName.목원대학교]: 'mwu.png',
	// [UniversityName.을지대학교]: 'uju.png',
	[UniversityName.우송대학교]: 'wsu.png',
	[UniversityName.고려대학교세종캠퍼스]: 'ku_sj.png',
	[UniversityName.홍익대학교세종캠퍼스]: 'hiu_sj.png',
	[UniversityName.한국교원대학교]: 'knue.png',
	[UniversityName.공주대학교]: 'dkju.png',
	[UniversityName.공주교육대학교]: 'dkje.png',
	[UniversityName.충북대학교]: 'cbnu.png',
	[UniversityName.청주교육대학교]: 'cjue.png',
	[UniversityName.우송정보대]: 'wsit.png',
	[UniversityName.대전신학대학교]: 'djts.png',
	[UniversityName.중부대학교]: 'jobu.png',
	[UniversityName.충북도립대학교]: 'cptu.png',
	[UniversityName.한국폴리텍]: 'kptu.png',
	[UniversityName.한국침례신학대학교]: 'kbts.png',
	[UniversityName.대덕대학교]: 'dddu.png',
	[UniversityName.금강대학교]: 'dgru.png',
	[UniversityName.대전과학기술대학교]: 'dkiu.png',
	[UniversityName.꽃동네대학교]: 'cbfdu.png',
	[UniversityName.서원대학교]: 'cbswu.png',
	[UniversityName.청주대학교]: 'cbcju.png',
	[UniversityName.충북보건과학대학교]: 'cbchs.png',
	[UniversityName.충청대학교]: 'cbccu.png',
	[UniversityName['한국폴리텍대학교 청주캠퍼스']]: 'cbkpc.png',

	[UniversityName.경성대학교]: 'ks.png',
	[UniversityName.고신대학교]: 'kosin.png',
	[UniversityName.부경대학교]: 'pukyong.png',
	[UniversityName.국립부경대학교]: 'pukyong.png',

	[UniversityName.한국해양대학교]: 'kmou.png',
	[UniversityName.국립한국해양대학교]: 'kmou.png',

	[UniversityName.동명대학교]: 'tu.png',
	[UniversityName.동서대학교]: 'dongseo.png',
	[UniversityName.동아대학교]: 'donga.png',
	[UniversityName.동의대학교]: 'deu.png',
	[UniversityName.부산가톨릭대학교]: 'cup.png',
	[UniversityName.부산교육대학교]: 'bnue.png',
	[UniversityName.부산대학교]: 'pusan.png',
	[UniversityName.가야대학교]: 'kaya.png',
	[UniversityName.부산외국어대학교]: 'bufs.png',
	[UniversityName.신라대학교]: 'su.png',
	[UniversityName.영신대학교]: 'ysu.png',
	[UniversityName.인제대학교]: 'inje.png',
	[UniversityName.부산과학기술대학교]: 'bst.png',
	[UniversityName.동의과학대학교]: 'dus.png',
	[UniversityName.부산여자대학교]: 'bwu.png',
	[UniversityName.부산경상대학교]: 'bku.png',
	[UniversityName.부산보건대학교]: 'bhu.png',
	[UniversityName.부산예술대학교]: 'bau.png',
	[UniversityName.김해대학교]: 'khu.png',
	[UniversityName.동원과학기술대학교]: 'dit.png',
	[UniversityName.경남정보대학교]: 'kit.png',
	[UniversityName.대동대학교]: 'bddu.png',
	[UniversityName['한국폴리텍 VII 대학 부산캠퍼스']]: 'kpub.png',
	[UniversityName['한국폴리텍 VII 대학 동부산캠퍼스']]: 'kpub.png',

	// 대구
	[UniversityName.경북대학교]: 'dgknu.png',
	[UniversityName.경북과학대학교]: 'dgkst.png',
	[UniversityName.경북보건대학교]: 'dgkhu.png',
	[UniversityName.경일대학교]: 'dgkiu.png',
	[UniversityName.계명대학교]: 'dgkmu.png',
	[UniversityName.계명문화대학교]: 'dgkcu.png',
	[UniversityName.구미대학교]: 'dggmu.png',
	[UniversityName.금오공과대학교]: 'dgkit.png',
	[UniversityName.김천대학교]: 'dgkcu.png',
	[UniversityName.대경대학교]: 'dgdku.png',
	[UniversityName.대구가톨릭대학교]: 'dgcau.png',
	[UniversityName.대구경북과학기술원]: 'dgdgist.png',
	[UniversityName.대구공업대학교]: 'dgdit.png',
	[UniversityName.대구과학대학교]: 'dgdsu.png',
	[UniversityName.대구교육대학교]: 'dgdnue.png',
	[UniversityName.대구대학교]: 'dgdau.png',
	[UniversityName.대구보건대학교]: 'dgdhu.png',
	[UniversityName.대구예술대학교]: 'dgdart.png',
	[UniversityName.대구한의대학교]: 'dgdhu.png',
	[UniversityName.대신대학교]: 'dgdsu.png',
	[UniversityName.수성대학교]: 'dgssu.png',
	[UniversityName.영남대학교]: 'dgynu.png',
	[UniversityName.영남신학대학교]: 'dgyts.png',
	[UniversityName.영남외국어대학교]: 'dgyfu.png',
	[UniversityName.영남이공대학교]: 'dgyit.png',
	[UniversityName.영진전문대학교]: 'dgyju.png',
	[UniversityName.호산대학교]: 'dghsu.png',
	[UniversityName.경운대학교]: 'dgkwu.png',
	[UniversityName['한국폴리텍대학교 구미캠퍼스']]: 'dgkpug.png',
	[UniversityName['한국폴리텍대학교 대구캠퍼스']]: 'dgkpud.png',
	[UniversityName['한국폴리텍대학교 영남융합기술캠퍼스']]: 'dgkpuy.png',
	[UniversityName['한국폴리텍대학교 영주캠퍼스']]: 'dgkpuyj.png',

	// 천안
	[UniversityName.국립공주대학교]: 'caknu.png',
	[UniversityName.나사렛대학교]: 'canu.png',
	[UniversityName.남서울대학교]: 'cansu.png',
	[UniversityName.단국대학교]: 'cadku.png',
	[UniversityName.백석대학교]: 'cabu.png',
	[UniversityName.상명대학교]: 'casmu.png',
	[UniversityName.순천향대학교]: 'caschu.png',
	[UniversityName.한국기술교육대학교]: 'cakut.png',
	[UniversityName.유원대학교]: 'cauu.png',
	[UniversityName.호서대학교]: 'cahu.png',
	[UniversityName.연암대학교]: 'cayu.png',
	[UniversityName['한국폴리텍 IV 대학 아산캠퍼스']]: 'cakpau.png',

	//인천
	// [UniversityName.가천대학교]: 'icngcu.png',
	// [UniversityName.경인교육대학교]: 'icnginue.png',
	// [UniversityName.안양대학교]: 'icnayu.png',
	// [UniversityName.인천가톨릭대학교]: 'icniccu.png',
	// [UniversityName.인천대학교]: 'icninu.png',
	// [UniversityName.인하대학교]: 'icninha.png',
	// [UniversityName.청운대학교]: 'icncwu.png',
	// [UniversityName.경인여자대학교]: 'icngwu.png',
	// [UniversityName.인하공업전문대학]: 'icnitc.png',
	// [UniversityName.재능대학교]: 'icnjei.png',
	// [UniversityName['한국폴리텍 II 대학 인천캠퍼스']]: 'icnkopo.png',
	// [UniversityName.한국공학대학교]: 'icnkoreatech.png',
	// [UniversityName.연세대학교국제캠퍼스]: 'icnyonsei-ic.png',

	[UniversityName['한국폴리텍 I 대학 (서울캠퍼스)']]: 'selkps.png',
	[UniversityName.한국체육대학교]: 'selkns.png',
	[UniversityName.서울대학교]: 'selsnu.png',
	[UniversityName.서울과학기술대학교]: 'selstu.png',
	[UniversityName.화성의과학대학교]: 'kyghmu.png',
	[UniversityName.협성대학교]: 'kyghyu.png',
	[UniversityName.한경국립대학교]: 'kyghku.png',
	[UniversityName.한국항공대학교]: 'kyghau.png',
	[UniversityName.한국공학대학교]: 'icnkoreatech.png',
	[UniversityName['한국폴리텍 II 대학 인천캠퍼스']]: 'icnkopo.png',
	[UniversityName.인천대학교]: 'icninu.png',
	[UniversityName.국립한국교통대학교]: 'kygktu.png',
	[UniversityName.한국예술종합학교]: 'selkna.png',
	[UniversityName.서울시립대학교]: 'seluos.png',
	[UniversityName.서울교육대학교]: 'selsne.png',
	[UniversityName.인덕대학교]: 'selidu.png',
	[UniversityName.가천대학교]: 'kyggcu.png',
	[UniversityName.가톨릭대학교]: 'kygcuk.png',
	[UniversityName.재능대학교]: 'icnjei.png',
	[UniversityName.인하공업전문대학]: 'icnitc.png',
	[UniversityName.경인여자대학교]: 'icngwu.png',
	[UniversityName.청운대학교]: 'icncwu.png',
	[UniversityName.인하대학교]: 'icninha.png',
	[UniversityName.인천가톨릭대학교]: 'icniccu.png',
	[UniversityName.안양대학교]: 'icnayu.png',
	[UniversityName.경인교육대학교]: 'icnginue.png',
	[UniversityName.연세대학교국제캠퍼스]: 'icnyonsei-ic.png',
	[UniversityName.강남대학교]: 'kygknu.png',
	[UniversityName.경기대학교]: 'kygkyu.png',
	[UniversityName.경동대학교]: 'kygkdu.png',
	[UniversityName.경희대학교]: 'kygkhu.png',
	[UniversityName.숭의여자대학교]: 'selsew.png',
	[UniversityName.서일대학교]: 'selsiu.png',
	[UniversityName.서울여자간호대학교]: 'selscn.png',
	[UniversityName.삼육보건대학교]: 'selshuj.png',
	[UniversityName.명지전문대학]: 'selmjc.png',
	[UniversityName.동양미래대학교]: 'seldmu.png',
	[UniversityName.홍익대학교]: 'selhiu.png',
	[UniversityName.한양대학교]: 'selhyu.png',
	[UniversityName.한성대학교]: 'selhsu.png',
	[UniversityName.한국외국어대학교]: 'selhfs.png',
	[UniversityName.한국성서대학교]: 'selkbu.png',
	[UniversityName.총신대학교]: 'selcsu.png',
	[UniversityName.중앙대학교]: 'selcau.png',
	[UniversityName.장로회신학대학교]: 'selput.png',
	[UniversityName.이화여자대학교]: 'selewu.png',
	[UniversityName.숭실대학교]: 'selssu.png',
	[UniversityName.숙명여자대학교]: 'selsmw.png',
	[UniversityName.세종대학교]: 'selsju.png',
	[UniversityName.성신여자대학교]: 'selssw.png',
	[UniversityName.성공회대학교]: 'selskh.png',
	[UniversityName.서울한영대학교]: 'selshu.png',
	[UniversityName.서울여자대학교]: 'selswu.png',
	[UniversityName.서울기독대학교]: 'selscu.png',
	[UniversityName.서경대학교]: 'selsku.png',
	[UniversityName.서강대학교]: 'selsgu.png',
	[UniversityName.삼육대학교]: 'selsyu.png',
	[UniversityName.명지대학교]: 'selmju.png',
	[UniversityName.동덕여자대학교]: 'selddw.png',
	[UniversityName.동국대학교]: 'seldgu.png',
	[UniversityName.국민대학교]: 'selkmu.png',
	[UniversityName.광운대학교]: 'selkwu.png',
	[UniversityName.고려대학교]: 'selkor.png',
	[UniversityName.건국대학교]: 'selkku.png',
	[UniversityName.강서대학교]: 'selkcu.png',
	[UniversityName.감리신학대학교]: 'selmtu.png',
	[UniversityName.한양여자대학교]: 'selhyw.png',
	[UniversityName.배화여자대학교]: 'selbwu.png',
	[UniversityName.추계예술대학교]: 'selcua.png',
	[UniversityName.연세대학교]: 'selysn.png',
	[UniversityName.성균관대학교]: 'selskk.png',
	[UniversityName.덕성여자대학교]: 'seldsw.png',
	[UniversityName.대진대학교]: 'kygduu.png',
	[UniversityName.동양대학교]: 'kygdyu.png',
	[UniversityName.루터대학교]: 'kygltu.png',
	[UniversityName.서울신학대학교]: 'kygstu.png',
	[UniversityName.서울장신대학교]: 'kygsju.png',
	[UniversityName.성결대학교]: 'kygsku.png',
	[UniversityName.수원가톨릭대학교]: 'kygswu.png',
	[UniversityName.수원대학교]: 'kygsuu.png',
	[UniversityName.신한대학교]: 'kygshi.png',
	[UniversityName.아신대학교]: 'kygacts.png',
	[UniversityName.아주대학교]: 'kygaju.png',
	[UniversityName.예원예술대학교]: 'kygyau.png',
	[UniversityName.용인대학교]: 'kygyiu.png',
	[UniversityName.을지대학교]: 'kygeul.png',

	[UniversityName.중앙승가대학교]: 'kygjsu.png',
	[UniversityName.차의과학대학교]: 'kygcha.png',
	[UniversityName.칼빈대학교]: 'kygcuv.png',
	[UniversityName.평택대학교]: 'kygptk.png',
	[UniversityName.한세대학교]: 'kyghsu.png',
	[UniversityName.한신대학교]: 'kyghan.png',
	[UniversityName['한양대학교(ERICA)']]: 'kyghyeu.png',
};

export const UniversityEnglishName: Partial<Record<UniversityName, string>> = {
	[UniversityName.배재대학교]: 'Pai Chai University',
	[UniversityName.충남대학교]: 'Chungnam National University',
	[UniversityName.대전보건대학교]: 'Daejeon Health University',
	[UniversityName.대전대학교]: 'Daejeon University',
	[UniversityName.한밭대학교]: 'Hanbat National University',
	[UniversityName.KAIST]: 'Korea Advanced Institute of Scienceand Technology',
	[UniversityName.한남대학교]: 'Hannam University',
	[UniversityName.건양대학교메디컬캠퍼스]: 'Konyang University ',
	[UniversityName.건양대학교창의융합캠퍼스]: 'Konyang University ',
	[UniversityName.건양대학교]: 'Konyang University',
	[UniversityName.목원대학교]: 'Mokwon University',
	[UniversityName.을지대학교]: 'Eulji university',
	[UniversityName.우송대학교]: 'Woosong University',
	[UniversityName.고려대학교세종캠퍼스]: 'KOREA University Sejong Campus',
	[UniversityName.홍익대학교세종캠퍼스]: 'Hongik University Sejong Campus',
	[UniversityName.한국교원대학교]: 'Korea National University of Education',
	[UniversityName.공주대학교]: 'Kongju National University',
	[UniversityName.공주교육대학교]: 'Gongju National University of Education',
	[UniversityName.충북대학교]: 'Chungbuk National University',
	[UniversityName.청주교육대학교]: 'Cheongju National University of Education',
	[UniversityName.우송정보대]: 'Woosong College',
	[UniversityName.대전신학대학교]: 'Daejeon Theological University',
	[UniversityName.중부대학교]: 'Joongbu University',
	[UniversityName.충북도립대학교]: 'Chungbuk Provincial University',
	[UniversityName.한국폴리텍]: 'Korea Polytechnics',
	[UniversityName.한국침례신학대학교]: 'Korea Baptist Theological University and Seminary',
	[UniversityName.대덕대학교]: 'Daeduk University',
	[UniversityName.금강대학교]: 'Geumgang University',
	[UniversityName.대전과학기술대학교]: 'Daejeon Institute of Science and Technology',
	[UniversityName.꽃동네대학교]: 'Catholic Kkottongnae University',
	[UniversityName.서원대학교]: 'Seowon University',
	[UniversityName.청주대학교]: 'Cheongju University',
	[UniversityName.충북보건과학대학교]: 'Chungbuk Health & Science University',
	[UniversityName.충청대학교]: 'Chungcheong University',
	[UniversityName['한국폴리텍대학교 청주캠퍼스']]: 'Korea Polytechnics',

	//부산
	[UniversityName.경성대학교]: 'Kyungsung University ',
	[UniversityName.고신대학교]: 'Kosin University',
	[UniversityName.국립부경대학교]: 'Pukyong National University',
	[UniversityName.부경대학교]: 'Pukyong National University',
	[UniversityName.한국해양대학교]: 'National Korea Maritime & Ocean University',
	[UniversityName.국립한국해양대학교]: 'National Korea Maritime & Ocean University',

	[UniversityName.동명대학교]: 'Tongmyong University',
	[UniversityName.동서대학교]: 'Dongseo University',
	[UniversityName.동아대학교]: 'Dong-A University ',
	[UniversityName.동의대학교]: 'dong-eui University',
	[UniversityName.부산가톨릭대학교]: 'Busan Catholic University',
	[UniversityName.부산교육대학교]: 'Busan National University of Education',
	[UniversityName.부산대학교]: 'Pusan National University',
	[UniversityName.가야대학교]: 'Gaya University',
	[UniversityName.부산외국어대학교]: 'Busan University of Foreign Studies',
	[UniversityName.신라대학교]: 'Silla University',
	[UniversityName.영신대학교]: 'Youngnam Theological University and Seminary',
	[UniversityName.인제대학교]: 'Inje University',
	[UniversityName.부산과학기술대학교]: 'Busan Institute of Science and Technology',
	[UniversityName.동의과학대학교]: 'Dong-Eui Institute of Technology',
	[UniversityName.부산여자대학교]: "Busan Women's University",
	[UniversityName.부산경상대학교]: 'Busan Kyungsang College',
	[UniversityName.부산보건대학교]: 'Busan Health University',
	[UniversityName.부산예술대학교]: 'Busan Arts College',
	[UniversityName.김해대학교]: 'Gimhae University',
	[UniversityName.동원과학기술대학교]: 'Dongwon Institute of Science And Technology',
	[UniversityName.경남정보대학교]: 'Kyungnam College of Information & Technology',
	[UniversityName.대동대학교]: 'Daedong University',
	[UniversityName['한국폴리텍 VII 대학 부산캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍 VII 대학 동부산캠퍼스']]: 'Korea Polytechnics',

	//대구
	[UniversityName.경북대학교]: 'Kyungpook National University',
	[UniversityName.경북과학대학교]: 'Kyongbuk Science University',
	[UniversityName.경북보건대학교]: 'Gyeongbuk College of Health',
	[UniversityName.경일대학교]: 'Kyungil University',
	[UniversityName.계명대학교]: 'Keimyung University',
	[UniversityName.계명문화대학교]: 'Keimyung College University',
	[UniversityName.구미대학교]: 'Gumi University',
	[UniversityName.금오공과대학교]: 'Kumoh National Institute of Technology',
	[UniversityName.김천대학교]: 'Gimcheon University',
	[UniversityName.대경대학교]: 'Daekyeung University',
	[UniversityName.대구가톨릭대학교]: 'Daegu Catholic University',
	[UniversityName.대구경북과학기술원]: 'Daegu Gyeongbuk Institute of Science & Technology (DGIST)',
	[UniversityName.대구공업대학교]: 'Daegu Technical University',
	[UniversityName.대구과학대학교]: 'Taegu Science University',
	[UniversityName.대구교육대학교]: 'Daegu National University of Education',
	[UniversityName.대구대학교]: 'Daegu University',
	[UniversityName.대구보건대학교]: 'Daegu Health College',
	[UniversityName.대구예술대학교]: 'Daegu Arts University',
	[UniversityName.대구한의대학교]: 'Daegu Haany University',
	[UniversityName.대신대학교]: 'Daeshin University',
	[UniversityName.수성대학교]: 'Suseong University',
	[UniversityName.영남대학교]: 'Yeungnam University',
	[UniversityName.영남신학대학교]: 'Youngnam Theological University and Seminary',
	[UniversityName.영남외국어대학교]: 'Youngnam Foreign Language College',
	[UniversityName.영남이공대학교]: 'Yeungnam University College',
	[UniversityName.영진전문대학교]: 'Yeungjin University',
	[UniversityName.호산대학교]: 'Hosan University',
	[UniversityName.경운대학교]: 'KyungWoon University',
	[UniversityName['한국폴리텍대학교 구미캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍대학교 대구캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍대학교 영남융합기술캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍대학교 영주캠퍼스']]: 'Korea Polytechnics',

	//천안
	[UniversityName.국립공주대학교]: 'Kongju National University',
	[UniversityName.나사렛대학교]: 'Korea Nazarene University',
	[UniversityName.남서울대학교]: 'Namseoul University',
	[UniversityName.단국대학교]: 'Dankook University',
	[UniversityName.백석대학교]: 'Baekseok University',
	[UniversityName.상명대학교]: 'Sangmyung University',
	[UniversityName.순천향대학교]: 'Soonchunhyang University',
	[UniversityName.한국기술교육대학교]: 'Korea University of Technology and Education',
	[UniversityName.유원대학교]: 'U1 University',
	[UniversityName.호서대학교]: 'Hoseo University',
	[UniversityName.연암대학교]: 'Yonam College',
	[UniversityName['한국폴리텍 IV 대학 아산캠퍼스']]: 'Korea Polytechnics',

	//인천
	[UniversityName.가천대학교]: 'Gachon University',
	[UniversityName.경인교육대학교]: 'Gyeongin National University of Education',
	[UniversityName.안양대학교]: 'Anyang University',
	[UniversityName.인천가톨릭대학교]: 'Incheon Catholic University',
	[UniversityName.인천대학교]: 'Incheon National University',
	[UniversityName.인하대학교]: 'Inha University',
	[UniversityName.청운대학교]: 'Chungwoon University',
	[UniversityName.경인여자대학교]: "Kyung-in Women's University",
	[UniversityName.인하공업전문대학]: 'Inha Technical College',
	[UniversityName.재능대학교]: 'JEI University',
	[UniversityName['한국폴리텍 II 대학 인천캠퍼스']]: 'Korea Polytechnics',
	[UniversityName.한국공학대학교]: 'Tech University of Korea',
	[UniversityName.연세대학교국제캠퍼스]: 'Yonsei University',
};

const baseUrl = 'https://sometimes-resources.s3.ap-northeast-2.amazonaws.com/univ/';

const createImageUrl = (univ: UniversityName) => `${baseUrl}${UniversityImage[univ]}`;

export const getUnivLogo = (univ: UniversityName) => createImageUrl(univ);

export const getSmartUnivLogoUrl = (univCode: string) => `${baseUrl}${univCode.toLowerCase()}.png`;
