export enum UniversityName {
	배재대학교 = '배재대학교',
	충남대학교 = '충남대학교',
	대전보건대학교 = '대전보건대학교',
	대전대학교 = '대전대학교',
	한밭대학교 = '한밭대학교',
	한남대학교 = '한남대학교',
	건양대학교메디컬캠퍼스 = '건양대학교 메디컬캠퍼스',
	건양대학교창의융합캠퍼스 = '건양대학교 창의융합캠퍼스',
	KAIST = 'KAIST',
	건양대학교 = '건양대학교',
	목원대학교 = '목원대학교',
	을지대학교 = '을지대학교',
	우송대학교 = '우송대학교',
	고려대학교세종캠퍼스 = '고려대학교 세종캠퍼스',
	홍익대학교세종캠퍼스 = '홍익대학교 세종캠퍼스',
	한국교원대학교 = '한국교원대학교',
	공주대학교 = '공주대학교',
	공주교육대학교 = '공주교육대학교',
	충북대학교 = '충북대학교',
	청주교육대학교 = '청주교육대학교',
	경성대학교 = '경성대학교',
	고신대학교 = '고신대학교',
	부경대학교 = '부경대학교',
	국립부경대학교 = '국립부경대학교',
	한국해양대학교 = '한국해양대학교',
	국립한국해양대학교 = '국립한국해양대학교',
	동명대학교 = '동명대학교',
	동서대학교 = '동서대학교',
	동아대학교 = '동아대학교',
	동의대학교 = '동의대학교',
	부산가톨릭대학교 = '부산가톨릭대학교',
	부산교육대학교 = '부산교육대학교',
	부산대학교 = '부산대학교',
	가야대학교 = '가야대학교',
	부산외국어대학교 = '부산외국어대학교',
	신라대학교 = '신라대학교',
	영신대학교 = '영신대학교',
	인제대학교 = '인제대학교',
	부산과학기술대학교 = '부산과학기술대학교',
	동의과학대학교 = '동의과학대학교',
	부산여자대학교 = '부산여자대학교',
	부산경상대학교 = '부산경상대학교',
	부산보건대학교 = '부산보건대학교',
	부산예술대학교 = '부산예술대학교',
	김해대학교 = '김해대학교',
	동원과학기술대학교 = '동원과학기술대학교',
	경남정보대학교 = '경남정보대학교',
	대동대학교 = '대동대학교',
	'한국폴리텍 VII 대학 부산캠퍼스' = '한국폴리텍 VII 대학 부산캠퍼스',
	'한국폴리텍 VII 대학 동부산캠퍼스' = '한국폴리텍 VII 대학 동부산캠퍼스',
}

export const UniversityImage: Record<UniversityName, string> = {
	[UniversityName.배재대학교]: 'bju.png',
	[UniversityName.충남대학교]: 'cnu.png',
	[UniversityName.대전보건대학교]: 'dbu.png',
	[UniversityName.대전대학교]: 'dju.png',
	[UniversityName.한밭대학교]: 'hbu.png',
	[UniversityName.KAIST]: 'kaist.png',
	[UniversityName.한남대학교]: 'hnu.png',
	[UniversityName.건양대학교메디컬캠퍼스]: 'kyu.png',
	[UniversityName.건양대학교창의융합캠퍼스]: 'kyu.png',
	[UniversityName.건양대학교]: 'kyu.png',
	[UniversityName.목원대학교]: 'mwu.png',
	[UniversityName.을지대학교]: 'uju.png',
	[UniversityName.우송대학교]: 'wsu.png',
	[UniversityName.고려대학교세종캠퍼스]: 'kau.png',
	[UniversityName.홍익대학교세종캠퍼스]: 'hiu.png',
	[UniversityName.한국교원대학교]: 'knu.png',
	[UniversityName.공주대학교]: 'kgu.png',
	[UniversityName.공주교육대학교]: 'keu.png',
	[UniversityName.충북대학교]: 'cbu.png',
	[UniversityName.청주교육대학교]: 'ceu.png',
	[UniversityName.경성대학교]: 'ks.png',
	[UniversityName.고신대학교]: 'kosin.png',
	[UniversityName.부경대학교]: 'pukyong.png',
	[UniversityName.국립부경대학교]: 'pukyong.png',

	[UniversityName.한국해양대학교]: 'kmou.png',
	[UniversityName.국립한국해양대학교]: 'kmou.png',

	[UniversityName.동명대학교]: 'tu.png',
	[UniversityName.동서대학교]: 'dongseo.png',
	[UniversityName.동아대학교]: 'donga.png',
	[UniversityName.동의대학교]: 'deu.png',
	[UniversityName.부산가톨릭대학교]: 'cup.png',
	[UniversityName.부산교육대학교]: 'bnue.png',
	[UniversityName.부산대학교]: 'pusan.png',
	[UniversityName.가야대학교]: 'kaya.png',
	[UniversityName.부산외국어대학교]: 'bufs.png',
	[UniversityName.신라대학교]: 'su.png',
	[UniversityName.영신대학교]: 'ysu.png',
	[UniversityName.인제대학교]: 'inje.png',
	[UniversityName.부산과학기술대학교]: 'bst.png',
	[UniversityName.동의과학대학교]: 'dus.png',
	[UniversityName.부산여자대학교]: 'bwu.png',
	[UniversityName.부산경상대학교]: 'bku.png',
	[UniversityName.부산보건대학교]: 'bhu.png',
	[UniversityName.부산예술대학교]: 'bau.png',
	[UniversityName.김해대학교]: 'khu.png',
	[UniversityName.동원과학기술대학교]: 'dit.png',
	[UniversityName.경남정보대학교]: 'kit.png',
	[UniversityName.대동대학교]: 'bddu.png',
	[UniversityName['한국폴리텍 VII 대학 부산캠퍼스']]: 'kpub.png',
	[UniversityName['한국폴리텍 VII 대학 동부산캠퍼스']]: 'kpub.png',
};

export const UniversityEnglishName: Record<UniversityName, string> = {
	[UniversityName.배재대학교]: 'Pai Chai University',
	[UniversityName.충남대학교]: 'Chungnam National University',
	[UniversityName.대전보건대학교]: 'Daejeon Health University',
	[UniversityName.대전대학교]: 'Daejeon University',
	[UniversityName.한밭대학교]: 'Hanbat National University',
	[UniversityName.KAIST]: 'Korea Advanced Institute of Scienceand Technology',
	[UniversityName.한남대학교]: 'Hannam University',
	[UniversityName.건양대학교메디컬캠퍼스]: 'Konyang University ',
	[UniversityName.건양대학교창의융합캠퍼스]: 'Konyang University ',
	[UniversityName.건양대학교]: 'Konyang University',
	[UniversityName.목원대학교]: 'Mokwon University',
	[UniversityName.을지대학교]: 'Eulji university',
	[UniversityName.우송대학교]: 'Woosong University',
	[UniversityName.고려대학교세종캠퍼스]: 'KOREA University Sejong Campus',
	[UniversityName.홍익대학교세종캠퍼스]: 'Hongik University Sejong Campus',
	[UniversityName.한국교원대학교]: 'knu.png',
	[UniversityName.공주대학교]: 'kgu.png',
	[UniversityName.공주교육대학교]: 'keu.png',
	[UniversityName.충북대학교]: 'cbu.png',
	[UniversityName.청주교육대학교]: 'ceu.png',

	//부산
	[UniversityName.경성대학교]: 'Kyungsung University ',
	[UniversityName.고신대학교]: 'Kosin University',
	[UniversityName.국립부경대학교]: 'Pukyong National University',
	[UniversityName.부경대학교]: 'Pukyong National University',
	[UniversityName.한국해양대학교]: 'National Korea Maritime & Ocean University',
	[UniversityName.국립한국해양대학교]: 'National Korea Maritime & Ocean University',

	[UniversityName.동명대학교]: 'Tongmyong University',
	[UniversityName.동서대학교]: 'Dongseo University',
	[UniversityName.동아대학교]: 'Dong-A University ',
	[UniversityName.동의대학교]: 'dong-eui University',
	[UniversityName.부산가톨릭대학교]: 'Busan Catholic University',
	[UniversityName.부산교육대학교]: 'Busan National University of Education',
	[UniversityName.부산대학교]: 'Pusan National University',
	[UniversityName.가야대학교]: 'Gaya University',
	[UniversityName.부산외국어대학교]: 'Busan University of Foreign Studies',
	[UniversityName.신라대학교]: 'Silla University',
	[UniversityName.영신대학교]: 'Youngnam Theological University and Seminary',
	[UniversityName.인제대학교]: 'Inje University',
	[UniversityName.부산과학기술대학교]: 'Busan Institute of Science and Technology',
	[UniversityName.동의과학대학교]: 'Dong-Eui Institute of Technology',
	[UniversityName.부산여자대학교]: "Busan Women's University",
	[UniversityName.부산경상대학교]: 'Busan Kyungsang College',
	[UniversityName.부산보건대학교]: 'Busan Health University',
	[UniversityName.부산예술대학교]: 'Busan Arts College',
	[UniversityName.김해대학교]: 'Gimhae University',
	[UniversityName.동원과학기술대학교]: 'Dongwon Institute of Science And Technology',
	[UniversityName.경남정보대학교]: 'Kyungnam College of Information & Technology',
	[UniversityName.대동대학교]: 'Daedong University',
	[UniversityName['한국폴리텍 VII 대학 부산캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍 VII 대학 동부산캠퍼스']]: 'Korea Polytechnics',
};

const baseUrl = 'https://sometimes-resources.s3.ap-northeast-2.amazonaws.com/univ/';

const createImageUrl = (univ: UniversityName) => `${baseUrl}${UniversityImage[univ]}`;

export const getUnivLogo = (univ: UniversityName) => createImageUrl(univ);

export const getSmartUnivLogoUrl = (univCode: string) => `${baseUrl}${univCode.toLowerCase()}.png`;
