export enum UniversityName {
	배재대학교 = '배재대학교',
	충남대학교 = '충남대학교',
	대전보건대학교 = '대전보건대학교',
	대전대학교 = '대전대학교',
	한밭대학교 = '한밭대학교',
	한남대학교 = '한남대학교',
	건양대학교메디컬캠퍼스 = '건양대학교 메디컬캠퍼스',
	건양대학교창의융합캠퍼스 = '건양대학교 창의융합캠퍼스',
	KAIST = 'KAIST',
	건양대학교 = '건양대학교',
	목원대학교 = '목원대학교',
	을지대학교 = '을지대학교',
	우송대학교 = '우송대학교',
	고려대학교세종캠퍼스 = '고려대학교 세종캠퍼스',
	홍익대학교세종캠퍼스 = '홍익대학교 세종캠퍼스',
	한국교원대학교 = '한국교원대학교',

	공주대학교 = '공주대학교',
	공주교육대학교 = '공주교육대학교',
	충북대학교 = '충북대학교',
	청주교육대학교 = '청주교육대학교',
	경성대학교 = '경성대학교',
	고신대학교 = '고신대학교',
	부경대학교 = '부경대학교',
	국립부경대학교 = '국립부경대학교',
	한국해양대학교 = '한국해양대학교',
	국립한국해양대학교 = '국립한국해양대학교',
	동명대학교 = '동명대학교',
	동서대학교 = '동서대학교',
	동아대학교 = '동아대학교',
	동의대학교 = '동의대학교',
	부산가톨릭대학교 = '부산가톨릭대학교',
	부산교육대학교 = '부산교육대학교',
	부산대학교 = '부산대학교',
	가야대학교 = '가야대학교',
	부산외국어대학교 = '부산외국어대학교',
	신라대학교 = '신라대학교',
	영신대학교 = '영신대학교',
	인제대학교 = '인제대학교',
	부산과학기술대학교 = '부산과학기술대학교',
	동의과학대학교 = '동의과학대학교',
	부산여자대학교 = '부산여자대학교',
	부산경상대학교 = '부산경상대학교',
	부산보건대학교 = '부산보건대학교',
	부산예술대학교 = '부산예술대학교',
	김해대학교 = '김해대학교',
	동원과학기술대학교 = '동원과학기술대학교',
	경남정보대학교 = '경남정보대학교',
	대동대학교 = '대동대학교',
	'한국폴리텍 VII 대학 부산캠퍼스' = '한국폴리텍 VII 대학 부산캠퍼스',
	'한국폴리텍 VII 대학 동부산캠퍼스' = '한국폴리텍 VII 대학 동부산캠퍼스',
	우송정보대 = '우송정보대',
	대전신학대학교 = '대전신학대학교',
	중부대학교 = '중부대학교',
	충북도립대학교 = '충북도립대학교',
	한국폴리텍 = '한국폴리텍',
	한국침례신학대학교 = '한국침례신학대학교',
	대덕대학교 = '대덕대학교',
	금강대학교 = '금강대학교',
	대전과학기술대학교 = '대전과학기술대학교',
	꽃동네대학교 = '꽃동네대학교',
	서원대학교 = '서원대학교',
	청주대학교 = '청주대학교',
	충북보건과학대학교 = '충북보건과학대학교',
	충청대학교 = '충청대학교',
	'한국폴리텍대학교 청주캠퍼스' = '한국폴리텍대학교 청주캠퍼스',

	경북대학교 = '경북대학교',
	경북과학대학교 = '경북과학대학교',
	경북보건대학교 = '경북보건대학교',
	경일대학교 = '경일대학교',
	계명대학교 = '계명대학교',
	계명문화대학교 = '계명문화대학교',
	구미대학교 = '구미대학교',
	금오공과대학교 = '금오공과대학교',
	김천대학교 = '김천대학교',
	대경대학교 = '대경대학교',
	대구가톨릭대학교 = '대구가톨릭대학교',
	대구경북과학기술원 = '대구경북과학기술원',
	대구공업대학교 = '대구공업대학교',
	대구과학대학교 = '대구과학대학교',
	대구교육대학교 = '대구교육대학교',
	대구대학교 = '대구대학교',
	대구보건대학교 = '대구보건대학교',
	대구예술대학교 = '대구예술대학교',
	대구한의대학교 = '대구한의대학교',
	대신대학교 = '대신대학교',
	수성대학교 = '수성대학교',
	영남대학교 = '영남대학교',
	영남신학대학교 = '영남신학대학교',
	영남외국어대학교 = '영남외국어대학교',
	영남이공대학교 = '영남이공대학교',
	영진전문대학교 = '영진전문대학교',
	호산대학교 = '호산대학교',
	경운대학교 = '경운대학교',
	'한국폴리텍대학교 구미캠퍼스' = '한국폴리텍대학교 구미캠퍼스',
	'한국폴리텍대학교 대구캠퍼스' = '한국폴리텍대학교 대구캠퍼스',
	'한국폴리텍대학교 영남융합기술캠퍼스' = '한국폴리텍대학교 영남융합기술캠퍼스',
	'한국폴리텍대학교 영주캠퍼스' = '한국폴리텍대학교 영주캠퍼스',

	// 천안
	국립공주대학교 = '국립공주대학교',
	나사렛대학교 = '나사렛대학교',
	남서울대학교 = '남서울대학교',

	백석대학교 = '백석대학교',
	상명대학교 = '상명대학교',

	한국기술교육대학교 = '한국기술교육대학교',
	유원대학교 = '유원대학교',
	호서대학교 = '호서대학교',
	연암대학교 = '연암대학교',
	'한국폴리텍 IV 대학 아산캠퍼스' = '한국폴리텍 IV 대학 아산캠퍼스',
	'한국폴리텍 I 대학 (서울캠퍼스)' = '한국폴리텍 I 대학 (서울캠퍼스)',
	한국체육대학교 = '한국체육대학교',
	서울대학교 = '서울대학교',
	서울과학기술대학교 = '서울과학기술대학교',
	화성의과학대학교 = '화성의과학대학교',
	협성대학교 = '협성대학교',
	한경국립대학교 = '한경국립대학교',
	한국항공대학교 = '한국항공대학교',
	한국공학대학교 = '한국공학대학교',

	'한국폴리텍 II 대학 인천캠퍼스' = '한국폴리텍 II 대학 인천캠퍼스',
	인천대학교 = '인천대학교',
	국립한국교통대학교 = '국립한국교통대학교',
	한국예술종합학교 = '한국예술종합학교',
	서울시립대학교 = '서울시립대학교',
	서울교육대학교 = '서울교육대학교',
	인덕대학교 = '인덕대학교',
	가천대학교 = '가천대학교',
	가톨릭대학교 = '가톨릭대학교',
	재능대학교 = '재능대학교',
	인하공업전문대학 = '인하공업전문대학',
	경인여자대학교 = '경인여자대학교',
	청운대학교 = '청운대학교',
	인하대학교 = '인하대학교',
	인천가톨릭대학교 = '인천가톨릭대학교',
	안양대학교 = '안양대학교',
	경인교육대학교 = '경인교육대학교',
	연세대학교국제캠퍼스 = '연세대학교국제캠퍼스',
	강남대학교 = '강남대학교',
	경기대학교 = '경기대학교',
	경동대학교 = '경동대학교',
	경희대학교 = '경희대학교',
	숭의여자대학교 = '숭의여자대학교',
	서일대학교 = '서일대학교',
	서울여자간호대학교 = '서울여자간호대학교',
	삼육보건대학교 = '삼육보건대학교',
	명지전문대학 = '명지전문대학',
	동양미래대학교 = '동양미래대학교',
	홍익대학교 = '홍익대학교',
	한양대학교 = '한양대학교',
	한성대학교 = '한성대학교',
	한국외국어대학교 = '한국외국어대학교',
	한국성서대학교 = '한국성서대학교',
	총신대학교 = '총신대학교',
	중앙대학교 = '중앙대학교',
	장로회신학대학교 = '장로회신학대학교',
	이화여자대학교 = '이화여자대학교',
	숭실대학교 = '숭실대학교',
	숙명여자대학교 = '숙명여자대학교',
	세종대학교 = '세종대학교',
	성신여자대학교 = '성신여자대학교',
	성공회대학교 = '성공회대학교',
	서울한영대학교 = '서울한영대학교',
	서울여자대학교 = '서울여자대학교',
	서울기독대학교 = '서울기독대학교',
	서경대학교 = '서경대학교',
	서강대학교 = '서강대학교',
	삼육대학교 = '삼육대학교',
	명지대학교 = '명지대학교',
	동덕여자대학교 = '동덕여자대학교',
	동국대학교 = '동국대학교',
	국민대학교 = '국민대학교',
	광운대학교 = '광운대학교',
	고려대학교 = '고려대학교',
	건국대학교 = '건국대학교',
	강서대학교 = '강서대학교',
	감리신학대학교 = '감리신학대학교',
	한양여자대학교 = '한양여자대학교',
	배화여자대학교 = '배화여자대학교',
	추계예술대학교 = '추계예술대학교',
	연세대학교 = '연세대학교',
	성균관대학교 = '성균관대학교',
	덕성여자대학교 = '덕성여자대학교',
	단국대학교 = '단국대학교',
	대진대학교 = '대진대학교',
	동양대학교 = '동양대학교',
	루터대학교 = '루터대학교',
	서울신학대학교 = '서울신학대학교',
	서울장신대학교 = '서울장신대학교',
	성결대학교 = '성결대학교',
	수원가톨릭대학교 = '수원가톨릭대학교',
	수원대학교 = '수원대학교',
	신한대학교 = '신한대학교',
	아신대학교 = '아신대학교',
	아주대학교 = '아주대학교',
	예원예술대학교 = '예원예술대학교',
	용인대학교 = '용인대학교',

	중앙승가대학교 = '중앙승가대학교',
	차의과학대학교 = '차의과학대학교',
	칼빈대학교 = '칼빈대학교',
	평택대학교 = '평택대학교',
	한세대학교 = '한세대학교',
	한신대학교 = '한신대학교',
	'한양대학교(ERICA)' = '한양대학교(ERICA)',
	순천향대학교 = '순천향대학교',

	// 광주광역시
	광신대학교 = '광신대학교',
	광주과학기술원 = '광주과학기술원',
	광주교육대학교 = '광주교육대학교',
	광주대학교 = '광주대학교',
	광주여자대학교 = '광주여자대학교',
	남부대학교 = '남부대학교',
	송원대학교 = '송원대학교',
	전남대학교 = '전남대학교',
	조선대학교 = '조선대학교',
	호남대학교 = '호남대학교',
	호남신학대학교 = '호남신학대학교',
	광주보건대학교 = '광주보건대학교',
	기독간호대학교 = '기독간호대학교',
	동강대학교 = '동강대학교',
	서영대학교 = '서영대학교',
	조선간호대학교 = '조선간호대학교',
	조선이공대학교 = '조선이공대학교',
	'한국폴리텍 V 대학 광주캠퍼스' = '한국폴리텍 V 대학 광주캠퍼스',
	동신대학교 = '동신대학교',
	나주대학교 = '나주대학교',
}

export const UniversityImage: Record<UniversityName, string> = {
	[UniversityName.배재대학교]: 'bju.webp',
	[UniversityName.충남대학교]: 'cnu.webp',
	[UniversityName.대전보건대학교]: 'dbu.webp',
	[UniversityName.대전대학교]: 'dju.webp',
	[UniversityName.한밭대학교]: 'hbu.webp',
	[UniversityName.KAIST]: 'kaist.webp',
	[UniversityName.한남대학교]: 'hnu.webp',
	[UniversityName.건양대학교메디컬캠퍼스]: 'kyu.webp',
	[UniversityName.건양대학교창의융합캠퍼스]: 'kyu.webp',
	[UniversityName.건양대학교]: 'kyu.webp',
	[UniversityName.목원대학교]: 'mwu.webp',
	// [UniversityName.을지대학교]: 'uju.webp',
	[UniversityName.우송대학교]: 'wsu.webp',
	[UniversityName.고려대학교세종캠퍼스]: 'ku_sj.webp',
	[UniversityName.홍익대학교세종캠퍼스]: 'hiu_sj.webp',
	[UniversityName.한국교원대학교]: 'knue.webp',
	[UniversityName.공주대학교]: 'dkju.webp',
	[UniversityName.공주교육대학교]: 'dkje.webp',
	[UniversityName.충북대학교]: 'cbnu.webp',
	[UniversityName.청주교육대학교]: 'cjue.webp',
	[UniversityName.우송정보대]: 'wsit.webp',
	[UniversityName.대전신학대학교]: 'djts.webp',
	[UniversityName.중부대학교]: 'jobu.webp',
	[UniversityName.충북도립대학교]: 'cptu.webp',
	[UniversityName.한국폴리텍]: 'kptu.webp',
	[UniversityName.한국침례신학대학교]: 'kbts.webp',
	[UniversityName.대덕대학교]: 'dddu.webp',
	[UniversityName.금강대학교]: 'dgru.webp',
	[UniversityName.대전과학기술대학교]: 'dkiu.webp',
	[UniversityName.꽃동네대학교]: 'cbfdu.webp',
	[UniversityName.서원대학교]: 'cbswu.webp',
	[UniversityName.청주대학교]: 'cbcju.webp',
	[UniversityName.충북보건과학대학교]: 'cbchs.webp',
	[UniversityName.충청대학교]: 'cbccu.webp',
	[UniversityName['한국폴리텍대학교 청주캠퍼스']]: 'cbkpc.webp',

	[UniversityName.경성대학교]: 'ks.webp',
	[UniversityName.고신대학교]: 'kosin.webp',
	[UniversityName.부경대학교]: 'pukyong.webp',
	[UniversityName.국립부경대학교]: 'pukyong.webp',

	[UniversityName.한국해양대학교]: 'kmou.webp',
	[UniversityName.국립한국해양대학교]: 'kmou.webp',

	[UniversityName.동명대학교]: 'tu.webp',
	[UniversityName.동서대학교]: 'dongseo.webp',
	[UniversityName.동아대학교]: 'donga.webp',
	[UniversityName.동의대학교]: 'deu.webp',
	[UniversityName.부산가톨릭대학교]: 'cup.webp',
	[UniversityName.부산교육대학교]: 'bnue.webp',
	[UniversityName.부산대학교]: 'pusan.webp',
	[UniversityName.가야대학교]: 'kaya.webp',
	[UniversityName.부산외국어대학교]: 'bufs.webp',
	[UniversityName.신라대학교]: 'su.webp',
	[UniversityName.영신대학교]: 'ysu.webp',
	[UniversityName.인제대학교]: 'inje.webp',
	[UniversityName.부산과학기술대학교]: 'bst.webp',
	[UniversityName.동의과학대학교]: 'dus.webp',
	[UniversityName.부산여자대학교]: 'bwu.webp',
	[UniversityName.부산경상대학교]: 'bku.webp',
	[UniversityName.부산보건대학교]: 'bhu.webp',
	[UniversityName.부산예술대학교]: 'bau.webp',
	[UniversityName.김해대학교]: 'khu.webp',
	[UniversityName.동원과학기술대학교]: 'dit.webp',
	[UniversityName.경남정보대학교]: 'kit.webp',
	[UniversityName.대동대학교]: 'bddu.webp',
	[UniversityName['한국폴리텍 VII 대학 부산캠퍼스']]: 'kpub.webp',
	[UniversityName['한국폴리텍 VII 대학 동부산캠퍼스']]: 'kpub.webp',

	// 대구
	[UniversityName.경북대학교]: 'dgknu.webp',
	[UniversityName.경북과학대학교]: 'dgkst.webp',
	[UniversityName.경북보건대학교]: 'dgkhu.webp',
	[UniversityName.경일대학교]: 'dgkiu.webp',
	[UniversityName.계명대학교]: 'dgkmu.webp',
	[UniversityName.계명문화대학교]: 'dgkcu.webp',
	[UniversityName.구미대학교]: 'dggmu.webp',
	[UniversityName.금오공과대학교]: 'dgkit.webp',
	[UniversityName.김천대학교]: 'dgkcu.webp',
	[UniversityName.대경대학교]: 'dgdku.webp',
	[UniversityName.대구가톨릭대학교]: 'dgcau.webp',
	[UniversityName.대구경북과학기술원]: 'dgdgist.webp',
	[UniversityName.대구공업대학교]: 'dgdit.webp',
	[UniversityName.대구과학대학교]: 'dgdsu.webp',
	[UniversityName.대구교육대학교]: 'dgdnue.webp',
	[UniversityName.대구대학교]: 'dgdau.webp',
	[UniversityName.대구보건대학교]: 'dgdhu.webp',
	[UniversityName.대구예술대학교]: 'dgdart.webp',
	[UniversityName.대구한의대학교]: 'dgdhu.webp',
	[UniversityName.대신대학교]: 'dgdsu.webp',
	[UniversityName.수성대학교]: 'dgssu.webp',
	[UniversityName.영남대학교]: 'dgynu.webp',
	[UniversityName.영남신학대학교]: 'dgyts.webp',
	[UniversityName.영남외국어대학교]: 'dgyfu.webp',
	[UniversityName.영남이공대학교]: 'dgyit.webp',
	[UniversityName.영진전문대학교]: 'dgyju.webp',
	[UniversityName.호산대학교]: 'dghsu.webp',
	[UniversityName.경운대학교]: 'dgkwu.webp',
	[UniversityName['한국폴리텍대학교 구미캠퍼스']]: 'dgkpug.webp',
	[UniversityName['한국폴리텍대학교 대구캠퍼스']]: 'dgkpud.webp',
	[UniversityName['한국폴리텍대학교 영남융합기술캠퍼스']]: 'dgkpuy.webp',
	[UniversityName['한국폴리텍대학교 영주캠퍼스']]: 'dgkpuyj.webp',

	// 천안
	[UniversityName.국립공주대학교]: 'caknu.webp',
	[UniversityName.나사렛대학교]: 'canu.webp',
	[UniversityName.남서울대학교]: 'cansu.webp',
	[UniversityName.단국대학교]: 'cadku.webp',
	[UniversityName.백석대학교]: 'cabu.webp',
	[UniversityName.상명대학교]: 'casmu.webp',
	[UniversityName.순천향대학교]: 'caschu.webp',
	[UniversityName.한국기술교육대학교]: 'cakut.webp',
	[UniversityName.유원대학교]: 'cauu.webp',
	[UniversityName.호서대학교]: 'cahu.webp',
	[UniversityName.연암대학교]: 'cayu.webp',
	[UniversityName['한국폴리텍 IV 대학 아산캠퍼스']]: 'cakpau.webp',

	//인천
	// [UniversityName.가천대학교]: 'icngcu.webp',
	// [UniversityName.경인교육대학교]: 'icnginue.webp',
	// [UniversityName.안양대학교]: 'icnayu.webp',
	// [UniversityName.인천가톨릭대학교]: 'icniccu.webp',
	// [UniversityName.인천대학교]: 'icninu.webp',
	// [UniversityName.인하대학교]: 'icninha.webp',
	// [UniversityName.청운대학교]: 'icncwu.webp',
	// [UniversityName.경인여자대학교]: 'icngwu.webp',
	// [UniversityName.인하공업전문대학]: 'icnitc.webp',
	// [UniversityName.재능대학교]: 'icnjei.webp',
	// [UniversityName['한국폴리텍 II 대학 인천캠퍼스']]: 'icnkopo.webp',
	// [UniversityName.한국공학대학교]: 'icnkoreatech.webp',
	// [UniversityName.연세대학교국제캠퍼스]: 'icnyonsei-ic.webp',

	[UniversityName['한국폴리텍 I 대학 (서울캠퍼스)']]: 'selkps.webp',
	[UniversityName.한국체육대학교]: 'selkns.webp',
	[UniversityName.서울대학교]: 'selsnu.webp',
	[UniversityName.서울과학기술대학교]: 'selstu.webp',
	[UniversityName.화성의과학대학교]: 'kyghmu.webp',
	[UniversityName.협성대학교]: 'kyghyu.webp',
	[UniversityName.한경국립대학교]: 'kyghku.webp',
	[UniversityName.한국항공대학교]: 'kyghau.webp',
	[UniversityName.한국공학대학교]: 'icnkoreatech.webp',
	[UniversityName['한국폴리텍 II 대학 인천캠퍼스']]: 'icnkopo.webp',
	[UniversityName.인천대학교]: 'icninu.webp',
	[UniversityName.국립한국교통대학교]: 'kygktu.webp',
	[UniversityName.한국예술종합학교]: 'selkna.webp',
	[UniversityName.서울시립대학교]: 'seluos.webp',
	[UniversityName.서울교육대학교]: 'selsne.webp',
	[UniversityName.인덕대학교]: 'selidu.webp',
	[UniversityName.가천대학교]: 'kyggcu.webp',
	[UniversityName.가톨릭대학교]: 'kygcuk.webp',
	[UniversityName.재능대학교]: 'icnjei.webp',
	[UniversityName.인하공업전문대학]: 'icnitc.webp',
	[UniversityName.경인여자대학교]: 'icngwu.webp',
	[UniversityName.청운대학교]: 'icncwu.webp',
	[UniversityName.인하대학교]: 'icninha.webp',
	[UniversityName.인천가톨릭대학교]: 'icniccu.webp',
	[UniversityName.안양대학교]: 'icnayu.webp',
	[UniversityName.경인교육대학교]: 'icnginue.webp',
	[UniversityName.연세대학교국제캠퍼스]: 'icnyonsei-ic.webp',
	[UniversityName.강남대학교]: 'kygknu.webp',
	[UniversityName.경기대학교]: 'kygkyu.webp',
	[UniversityName.경동대학교]: 'kygkdu.webp',
	[UniversityName.경희대학교]: 'kygkhu.webp',
	[UniversityName.숭의여자대학교]: 'selsew.webp',
	[UniversityName.서일대학교]: 'selsiu.webp',
	[UniversityName.서울여자간호대학교]: 'selscn.webp',
	[UniversityName.삼육보건대학교]: 'selshuj.webp',
	[UniversityName.명지전문대학]: 'selmjc.webp',
	[UniversityName.동양미래대학교]: 'seldmu.webp',
	[UniversityName.홍익대학교]: 'selhiu.webp',
	[UniversityName.한양대학교]: 'selhyu.webp',
	[UniversityName.한성대학교]: 'selhsu.webp',
	[UniversityName.한국외국어대학교]: 'selhfs.webp',
	[UniversityName.한국성서대학교]: 'selkbu.webp',
	[UniversityName.총신대학교]: 'selcsu.webp',
	[UniversityName.중앙대학교]: 'selcau.webp',
	[UniversityName.장로회신학대학교]: 'selput.webp',
	[UniversityName.이화여자대학교]: 'selewu.webp',
	[UniversityName.숭실대학교]: 'selssu.webp',
	[UniversityName.숙명여자대학교]: 'selsmw.webp',
	[UniversityName.세종대학교]: 'selsju.webp',
	[UniversityName.성신여자대학교]: 'selssw.webp',
	[UniversityName.성공회대학교]: 'selskh.webp',
	[UniversityName.서울한영대학교]: 'selshu.webp',
	[UniversityName.서울여자대학교]: 'selswu.webp',
	[UniversityName.서울기독대학교]: 'selscu.webp',
	[UniversityName.서경대학교]: 'selsku.webp',
	[UniversityName.서강대학교]: 'selsgu.webp',
	[UniversityName.삼육대학교]: 'selsyu.webp',
	[UniversityName.명지대학교]: 'selmju.webp',
	[UniversityName.동덕여자대학교]: 'selddw.webp',
	[UniversityName.동국대학교]: 'seldgu.webp',
	[UniversityName.국민대학교]: 'selkmu.webp',
	[UniversityName.광운대학교]: 'selkwu.webp',
	[UniversityName.고려대학교]: 'selkor.webp',
	[UniversityName.건국대학교]: 'selkku.webp',
	[UniversityName.강서대학교]: 'selkcu.webp',
	[UniversityName.감리신학대학교]: 'selmtu.webp',
	[UniversityName.한양여자대학교]: 'selhyw.webp',
	[UniversityName.배화여자대학교]: 'selbwu.webp',
	[UniversityName.추계예술대학교]: 'selcua.webp',
	[UniversityName.연세대학교]: 'selysn.webp',
	[UniversityName.성균관대학교]: 'selskk.webp',
	[UniversityName.덕성여자대학교]: 'seldsw.webp',
	[UniversityName.대진대학교]: 'kygduu.webp',
	[UniversityName.동양대학교]: 'kygdyu.webp',
	[UniversityName.루터대학교]: 'kygltu.webp',
	[UniversityName.서울신학대학교]: 'kygstu.webp',
	[UniversityName.서울장신대학교]: 'kygsju.webp',
	[UniversityName.성결대학교]: 'kygsku.webp',
	[UniversityName.수원가톨릭대학교]: 'kygswu.webp',
	[UniversityName.수원대학교]: 'kygsuu.webp',
	[UniversityName.신한대학교]: 'kygshi.webp',
	[UniversityName.아신대학교]: 'kygacts.webp',
	[UniversityName.아주대학교]: 'kygaju.webp',
	[UniversityName.예원예술대학교]: 'kygyau.webp',
	[UniversityName.용인대학교]: 'kygyiu.webp',
	[UniversityName.을지대학교]: 'kygeul.webp',

	[UniversityName.중앙승가대학교]: 'kygjsu.webp',
	[UniversityName.차의과학대학교]: 'kygcha.webp',
	[UniversityName.칼빈대학교]: 'kygcuv.webp',
	[UniversityName.평택대학교]: 'kygptk.webp',
	[UniversityName.한세대학교]: 'kyghsu.webp',
	[UniversityName.한신대학교]: 'kyghan.webp',
	[UniversityName['한양대학교(ERICA)']]: 'kyghyeu.webp',

	// 광주광역시
	[UniversityName.광신대학교]: 'gwjksu.webp',
	[UniversityName.광주과학기술원]: 'gwjgist.webp',
	[UniversityName.광주교육대학교]: 'gwjgnue.webp',
	[UniversityName.광주대학교]: 'gwjgu.webp',
	[UniversityName.광주여자대학교]: 'gwjgwu.webp',
	[UniversityName.남부대학교]: 'gwjnbu.webp',
	[UniversityName.송원대학교]: 'gwjswu.webp',
	[UniversityName.전남대학교]: 'gwjgnu.webp',
	[UniversityName.조선대학교]: 'gwjcau.webp',
	[UniversityName.호남대학교]: 'gwjhu.webp',
	[UniversityName.호남신학대학교]: 'gwjhstu.webp',
	[UniversityName.광주보건대학교]: 'gwjghu.webp',
	[UniversityName.기독간호대학교]: 'gwjcc.webp',
	[UniversityName.동강대학교]: 'gwjdku.webp',
	[UniversityName.서영대학교]: 'gwjsyu.webp',
	[UniversityName.조선간호대학교]: 'gwjcn.webp',
	[UniversityName.조선이공대학교]: 'gwjcst.webp',
	[UniversityName['한국폴리텍 V 대학 광주캠퍼스']]: 'gwjkpu.webp',
	[UniversityName.동신대학교]: 'gwjdsu.webp',
	[UniversityName.나주대학교]: 'gwjnu.webp',
};

export const UniversityEnglishName: Partial<Record<UniversityName, string>> = {
	[UniversityName.배재대학교]: 'Pai Chai University',
	[UniversityName.충남대학교]: 'Chungnam National University',
	[UniversityName.대전보건대학교]: 'Daejeon Health University',
	[UniversityName.대전대학교]: 'Daejeon University',
	[UniversityName.한밭대학교]: 'Hanbat National University',
	[UniversityName.KAIST]: 'Korea Advanced Institute of Scienceand Technology',
	[UniversityName.한남대학교]: 'Hannam University',
	[UniversityName.건양대학교메디컬캠퍼스]: 'Konyang University ',
	[UniversityName.건양대학교창의융합캠퍼스]: 'Konyang University ',
	[UniversityName.건양대학교]: 'Konyang University',
	[UniversityName.목원대학교]: 'Mokwon University',
	[UniversityName.을지대학교]: 'Eulji university',
	[UniversityName.우송대학교]: 'Woosong University',
	[UniversityName.고려대학교세종캠퍼스]: 'KOREA University Sejong Campus',
	[UniversityName.홍익대학교세종캠퍼스]: 'Hongik University Sejong Campus',
	[UniversityName.한국교원대학교]: 'Korea National University of Education',
	[UniversityName.공주대학교]: 'Kongju National University',
	[UniversityName.공주교육대학교]: 'Gongju National University of Education',
	[UniversityName.충북대학교]: 'Chungbuk National University',
	[UniversityName.청주교육대학교]: 'Cheongju National University of Education',
	[UniversityName.우송정보대]: 'Woosong College',
	[UniversityName.대전신학대학교]: 'Daejeon Theological University',
	[UniversityName.중부대학교]: 'Joongbu University',
	[UniversityName.충북도립대학교]: 'Chungbuk Provincial University',
	[UniversityName.한국폴리텍]: 'Korea Polytechnics',
	[UniversityName.한국침례신학대학교]: 'Korea Baptist Theological University and Seminary',
	[UniversityName.대덕대학교]: 'Daeduk University',
	[UniversityName.금강대학교]: 'Geumgang University',
	[UniversityName.대전과학기술대학교]: 'Daejeon Institute of Science and Technology',
	[UniversityName.꽃동네대학교]: 'Catholic Kkottongnae University',
	[UniversityName.서원대학교]: 'Seowon University',
	[UniversityName.청주대학교]: 'Cheongju University',
	[UniversityName.충북보건과학대학교]: 'Chungbuk Health & Science University',
	[UniversityName.충청대학교]: 'Chungcheong University',
	[UniversityName['한국폴리텍대학교 청주캠퍼스']]: 'Korea Polytechnics',

	//부산
	[UniversityName.경성대학교]: 'Kyungsung University ',
	[UniversityName.고신대학교]: 'Kosin University',
	[UniversityName.국립부경대학교]: 'Pukyong National University',
	[UniversityName.부경대학교]: 'Pukyong National University',
	[UniversityName.한국해양대학교]: 'National Korea Maritime & Ocean University',
	[UniversityName.국립한국해양대학교]: 'National Korea Maritime & Ocean University',

	[UniversityName.동명대학교]: 'Tongmyong University',
	[UniversityName.동서대학교]: 'Dongseo University',
	[UniversityName.동아대학교]: 'Dong-A University ',
	[UniversityName.동의대학교]: 'dong-eui University',
	[UniversityName.부산가톨릭대학교]: 'Busan Catholic University',
	[UniversityName.부산교육대학교]: 'Busan National University of Education',
	[UniversityName.부산대학교]: 'Pusan National University',
	[UniversityName.가야대학교]: 'Gaya University',
	[UniversityName.부산외국어대학교]: 'Busan University of Foreign Studies',
	[UniversityName.신라대학교]: 'Silla University',
	[UniversityName.영신대학교]: 'Youngnam Theological University and Seminary',
	[UniversityName.인제대학교]: 'Inje University',
	[UniversityName.부산과학기술대학교]: 'Busan Institute of Science and Technology',
	[UniversityName.동의과학대학교]: 'Dong-Eui Institute of Technology',
	[UniversityName.부산여자대학교]: "Busan Women's University",
	[UniversityName.부산경상대학교]: 'Busan Kyungsang College',
	[UniversityName.부산보건대학교]: 'Busan Health University',
	[UniversityName.부산예술대학교]: 'Busan Arts College',
	[UniversityName.김해대학교]: 'Gimhae University',
	[UniversityName.동원과학기술대학교]: 'Dongwon Institute of Science And Technology',
	[UniversityName.경남정보대학교]: 'Kyungnam College of Information & Technology',
	[UniversityName.대동대학교]: 'Daedong University',
	[UniversityName['한국폴리텍 VII 대학 부산캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍 VII 대학 동부산캠퍼스']]: 'Korea Polytechnics',

	//대구
	[UniversityName.경북대학교]: 'Kyungpook National University',
	[UniversityName.경북과학대학교]: 'Kyongbuk Science University',
	[UniversityName.경북보건대학교]: 'Gyeongbuk College of Health',
	[UniversityName.경일대학교]: 'Kyungil University',
	[UniversityName.계명대학교]: 'Keimyung University',
	[UniversityName.계명문화대학교]: 'Keimyung College University',
	[UniversityName.구미대학교]: 'Gumi University',
	[UniversityName.금오공과대학교]: 'Kumoh National Institute of Technology',
	[UniversityName.김천대학교]: 'Gimcheon University',
	[UniversityName.대경대학교]: 'Daekyeung University',
	[UniversityName.대구가톨릭대학교]: 'Daegu Catholic University',
	[UniversityName.대구경북과학기술원]: 'Daegu Gyeongbuk Institute of Science & Technology (DGIST)',
	[UniversityName.대구공업대학교]: 'Daegu Technical University',
	[UniversityName.대구과학대학교]: 'Taegu Science University',
	[UniversityName.대구교육대학교]: 'Daegu National University of Education',
	[UniversityName.대구대학교]: 'Daegu University',
	[UniversityName.대구보건대학교]: 'Daegu Health College',
	[UniversityName.대구예술대학교]: 'Daegu Arts University',
	[UniversityName.대구한의대학교]: 'Daegu Haany University',
	[UniversityName.대신대학교]: 'Daeshin University',
	[UniversityName.수성대학교]: 'Suseong University',
	[UniversityName.영남대학교]: 'Yeungnam University',
	[UniversityName.영남신학대학교]: 'Youngnam Theological University and Seminary',
	[UniversityName.영남외국어대학교]: 'Youngnam Foreign Language College',
	[UniversityName.영남이공대학교]: 'Yeungnam University College',
	[UniversityName.영진전문대학교]: 'Yeungjin University',
	[UniversityName.호산대학교]: 'Hosan University',
	[UniversityName.경운대학교]: 'KyungWoon University',
	[UniversityName['한국폴리텍대학교 구미캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍대학교 대구캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍대학교 영남융합기술캠퍼스']]: 'Korea Polytechnics',
	[UniversityName['한국폴리텍대학교 영주캠퍼스']]: 'Korea Polytechnics',

	//천안
	[UniversityName.국립공주대학교]: 'Kongju National University',
	[UniversityName.나사렛대학교]: 'Korea Nazarene University',
	[UniversityName.남서울대학교]: 'Namseoul University',
	[UniversityName.단국대학교]: 'Dankook University',
	[UniversityName.백석대학교]: 'Baekseok University',
	[UniversityName.상명대학교]: 'Sangmyung University',
	[UniversityName.순천향대학교]: 'Soonchunhyang University',
	[UniversityName.한국기술교육대학교]: 'Korea University of Technology and Education',
	[UniversityName.유원대학교]: 'U1 University',
	[UniversityName.호서대학교]: 'Hoseo University',
	[UniversityName.연암대학교]: 'Yonam College',
	[UniversityName['한국폴리텍 IV 대학 아산캠퍼스']]: 'Korea Polytechnics',

	//인천
	[UniversityName.가천대학교]: 'Gachon University',
	[UniversityName.경인교육대학교]: 'Gyeongin National University of Education',
	[UniversityName.안양대학교]: 'Anyang University',
	[UniversityName.인천가톨릭대학교]: 'Incheon Catholic University',
	[UniversityName.인천대학교]: 'Incheon National University',
	[UniversityName.인하대학교]: 'Inha University',
	[UniversityName.청운대학교]: 'Chungwoon University',
	[UniversityName.경인여자대학교]: "Kyung-in Women's University",
	[UniversityName.인하공업전문대학]: 'Inha Technical College',
	[UniversityName.재능대학교]: 'JEI University',
	[UniversityName['한국폴리텍 II 대학 인천캠퍼스']]: 'Korea Polytechnics',
	[UniversityName.한국공학대학교]: 'Tech University of Korea',
	[UniversityName.연세대학교국제캠퍼스]: 'Yonsei University',
};

const baseUrl = 'https://sometimes-resources.s3.ap-northeast-2.amazonaws.com/univ/';
const DEFAULT_UNIV_LOGO = 'https://sometimes-resources.s3.ap-northeast-2.amazonaws.com/univ/default.webp';

const createImageUrl = (univ: UniversityName) => {
	const imageName = UniversityImage[univ];
	if (!imageName) {
		return DEFAULT_UNIV_LOGO;
	}
	return `${baseUrl}${imageName}`;
};

export const getUnivLogo = (univ: UniversityName) => createImageUrl(univ);

export const getSmartUnivLogoUrl = (univCode: string, country: 'kr' | 'jp' = 'kr') => {
	const code = country === 'jp' ? univCode : univCode.toLowerCase();
	return `${baseUrl}${code}.webp`;
};
